/*
 * Copyright 2017-2018 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
 /***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_ASW_DI 0x00u        /*!<@brief Analog switch is open (disabled) */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_FUNC6 0x06u         /*!<@brief Selects pin function 6 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name FC0_RXD_SDA_MOSI_DATA (number 92), U11[14]/U22[14]/FC0_USART_RXD
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (number 94), U11[13]/U22[13]/FC0_USART_TXD
  @{ */
/* @} */

/*! @name SWO (number 21), J9[1]/U18[12]/N4M_SWO
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_13_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_13_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_14_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO0_14_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_2_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_2_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_3_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_3_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_4_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_4_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO0_6_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO0_6_FUNC_ALT0 0x00u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_19_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_19_MODE_PULL_UP 0x02u
/*!
 * @brief Select Digital mode.: Enable Digital mode. Digital input is enabled. */
#define PIO1_28_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO1_28_FUNC_ALT0 0x00u
/*!
 * @brief Selects function mode (on-chip pull-up/pull-down resistor control).: Pull-up. Pull-up resistor enabled. */
#define PIO1_28_MODE_PULL_UP 0x02u

/*! @name PIO0_6 (number 89), J10[14]/U24[13]/FC3_SPI_SCK
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_COL1_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL1_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_COL1_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL1_PIN 6U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_COL1_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_2 (number 81), J10[20]/U24[12]/FC3_SPI_MISO
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_COL2_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL2_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_COL2_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL2_PIN 2U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_COL2_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_3 (number 83), J10[18]/U24[11]/FC3_SPI_MOSI
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_COL3_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_COL3_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL3_PIN 3U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_COL3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_4 (number 86), J10[16]/U24[14]/FC3_SPI_SSEL0
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_COL4_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL4_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_COL4_PORT 0U                  /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_COL4_PIN 4U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_COL4_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO0_13 (number 71), J13[9]/J13[10]/J18[8]/JS5[2]/FC1_I2C_SDA
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_ROW1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW1_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_ROW1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW1_PIN 13U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_ROW1_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO0_14 (number 72), J13[11]/J13[12]/J18[6]/JS4[2]/FC1_I2C_SCL
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_ROW2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW2_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_ROW2_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW2_PIN 14U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_ROW2_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO1_19 (number 58), J18[4]/ISP_P1_19
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_ROW3_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW3_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_ROW3_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW3_PIN 19U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_ROW3_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PIO1_28 (number 73), J9[17]/J18[2]/EXP_ISP_P1_28
  @{ */

/* Symbols to be used with GPIO driver */
#define PINSFUNC_KEYSCAN_ROW4_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW4_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define PINSFUNC_KEYSCAN_ROW4_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define PINSFUNC_KEYSCAN_ROW4_PIN 28U                   /*!<@brief PORT pin number */
#define PINSFUNC_KEYSCAN_ROW4_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PinsFunc_keyscan(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
